# Generated by Django 6.0.7 on 2026-07-18 10:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('graph', 'Graph'), ('text', 'Text')], max_length=10)),
                ('question', models.TextField()),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing-task/')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('question', models.ManyToManyField(related_name='writing_tasks', to='writing.writingquestion')),
            ],
        ),
    ]
