# Generated by Django 6.0.7 on 2026-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forgot',
            field=models.BooleanField(default=False, verbose_name='Forgot Password'),
        ),
    ]
