# Generated by Django 6.0.7 on 2026-07-18 10:54

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reading Passage',
                'verbose_name_plural': 'Reading Passages',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('passages', models.ManyToManyField(to='reading.readingpassage')),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('bool', 'True False or Not Given'), ('blank', 'Fill in the blanks'), ('match', 'Matching'), ('answer', 'Answer the questions')], default='mcq', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='For type \'MCQ\':- ["a", "b", "c", "d"],    For type \'True/False/Not Given\':- ["True", "False", "Not Given"],   For type \'Fill in the blanks\':- null,    For type \'Matching\':- {"left":["1", "2", "3"], "right":["a", "b", "c"]},    For type \'Answer the questions\':- null', null=True)),
                ('answer', models.JSONField(blank=True, help_text='For type \'Matching\':- {"1": "a", "2": "b", "3": "c"},    For others: "Text" ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingpassage')),
            ],
            options={
                'verbose_name': 'Reading Question',
                'verbose_name_plural': 'Reading Questions',
            },
        ),
    ]
