# Generated by Django 6.0.7 on 2026-07-18 10:54

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField()),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=840))),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
            },
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3')], default=1)),
                ('audio', models.FileField(blank=True, null=True, upload_to='speaking_answers/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='speaking.questionset')),
            ],
        ),
    ]
